name: Deploy Coolify Webhook
on:
  workflow_run:
    workflows: ["Build and Deploy"]
    types: [completed]
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, ikaapp-web]
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy To Coolify
        run: |
          curl -X GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
